service: zal
provider:
  name: aws
  profile: default
  runtime: nodejs12.x

functions:
  svg-to-image:
    handler: handler.render
    memorySize: 1536MB
    timeout: 30
    events:
      - http:
          path: /
          method: post
